name: CI/CD Pipeline for Calculator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: redaben534
          password: ${{ github.action.secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ github.action.secrets.DOCKER_USERNAME }}/simple-calculator:latest .
          docker push ${{ github.action.secrets.DOCKER_USERNAME }}/simple-calculator:latest
  deploy:
    needs: docker-build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Azure (Example)
        if: success()
        run: |
          az login --service-principal -u ${{ github.action.secrets.AZURE_CLIENT_ID }} -p ${{ github.action.secrets.AZURE_SECRET }} --tenant ${{ github.action.secrets.AZURE_TENANT }}
          az webapp create --resource-group MyResourceGroup --plan MyAppServicePlan --name MyCalculatorApp --deployment-container-image-name redaben534/simple-calculator:latest
