name: CI/CD Pipeline for Calculator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # Assurez-vous que ce secret est bien défini dans GitHub
          password: ${{ secrets.DOCKER_PASSWORD }}   # Assurez-vous que ce secret est bien défini dans GitHub

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-calculator:latest "./DevOps P/app"
          docker push ${{ secrets.DOCKER_USERNAME }}/simple-calculator:latest

  deploy:
    needs: docker-build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Azure
        if: success()
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_SECRET }} --tenant ${{ secrets.AZURE_TENANT }}
          az webapp create --resource-group MyResourceGroup --plan MyAppServicePlan --name MyCalculatorApp --deployment-container-image-name ${{ secrets.DOCKER_USERNAME }}/simple-calculator:latest
