name: CI/CD Pipeline for Calculator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "redaben534" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t redaben534/simple-calculator:latest .
          docker push redaben534/simple-calculator:latest

  
