name: CI/CD Pipeline for Calculator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ github.action.secrets.DOCKER_PASSWORD }}" | docker login -u "redaben534" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t redaben534/simple-calculator:latest .
          docker push redaben534/simple-calculator:latest

  deploy:
    needs: docker-build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Azure (Example)
        if: success()
        run: |
          az login --service-principal -u ${{ github.action.secrets.AZURE_CLIENT_ID }} -p ${{ github.action.secrets.AZURE_SECRET }} --tenant ${{ github.action.secrets.AZURE_TENANT }}
          az webapp create --resource-group MyResourceGroup --plan MyAppServicePlan --name MyCalculatorApp --deployment-container-image-name redaben534/simple-calculator:latest
