name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "redaben534" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t redaben534/simple-calculator:latest .
          docker push redaben534/simple-calculator:latest
  sonarqube-analysis:
    runs-on: ubuntu-latest
    needs: docker-build  # Exécuter SonarQube après la build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 17 (Required for SonarQube)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install SonarScanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner.zip
          mv sonar-scanner-5.0.1.3006-linux sonar-scanner
          echo "$(pwd)/sonar-scanner/bin" >> $GITHUB_PATH

      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"
        run: |
          sonar-scanner \
            -Dsonar.projectKey=RJY-X_Calculator \
            -Dsonar.organization=rjy-x \
            -Dsonar.sources=main \
            -Dsonar.host.url=${SONAR_HOST_URL} \
            -Dsonar.login=${SONAR_TOKEN}
